name: Build and deploy Spring Boot app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Rename JAR to app.jar
        run: |
          mkdir -p package
          cp target/*.jar package/app.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app

      - name: Show contents of java-app
        run: ls -lh java-app

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A23292552FC34981AF5DC17CBB61D51B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A5385DDFF23E49DCA4983E3A83C9FD77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE3BFA43EFD0428E98C0FA29163414C5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'halwacitymarathon'
          package: 'java-app'
